=== kmishra-cell/gs_custom_build/configuration/Reference/streetreffiles/IDUniquenessCheckMatchKeySet.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT IDUniquenessCheckMatchKeySet (ENTITY+)>
<!ELEMENT ENTITY (IDENTIFIER)*>
<!ATTLIST ENTITY
        NAME CDATA #REQUIRED 
        TYPE (ISSU | ISSR | MRKT | FINS | FINR | CUST | EMPL | MRKX | EMRL | ACCT | DLER | DLBR | DREP | FPRO | BNCH | ISGR | CADF | FLDF | FCDF | ENTR | FIGR | IRGR | RTNG | STFD | PRVI | VHDF | MTRX | MTDI | APDF | PMUS | APLB | PCRL | PPED | ACIN | IADS | SPDC | IALG | SCAI | SCDF | IASA | SRLE
		| AUSR | AUGR | DCDF | EMGR | GUNT | GUGR | ISTY | ITGR | LAGR | PROD | PFTR | PDGR | PLNE | SUBD | SPRF | DWDF | NCDF | CYCH | BFDF | SSIS | ACTP | TXWH | EXAC | SLOC | CNTC | RGAT | RGRL | PRTY | MTTY | MDGR | JBDF | EINC | FRID | IRTY | ISPC | PXGD | RKFT | RICS | VRWN | PXDF | VRDF | GNPC 
    | GNPI | RLSC | RLSI | RLDF | INCS | UCPC | DCNG | PCFD | CVDF | GPCS | VSFD | BFRT | ENVR | PCGR | PATY | PART | ACGR | CUTY | ERGC | BNTY | RKFG | RKSD | RKSG | IAPU | EXTR | MTGR | FILF | WARC | WBND | WCAD | WCDP | WCRI | WCRP | WDTD | WENK | WENR | WIGR | WISK | WISL | WISR | WFXR | WGNR
    | WGNT | WHLD | WACK | WACS | WAGR | WMIC | WMTK | WIST | WITY | WLGR | WLMT | WLOT | WNCL | WNCS | WPAS | WPAT | WRTS | WRTV | WRTX | WPDK | WPGR | WPOS | WPRC | WPRM | WPTK | WRCP | WRIP | WWRA | WSTR | WTCL | WTGR | WTLT | WTRD | WTRN | WAAL | ACCS | ACRD | AGTR | BALH | EIST | EIAT | SCRD | PPRY | PAGR | WCRD | RPSP | RPTI) #REQUIRED 
        MATCH_FIELD CDATA #REQUIRED
        NEED_PREVALIDATION (Y|N|TRUE|FALSE) "N" 
        LOOKUPID_REQUIRED (Y|N|TRUE|FALSE) "N" 
        PRIMARY_IDENTIFIER CDATA ""
		SECONDARY_IDENTIFIER CDATA ""
        DUMMY_ACTIVITY_STATUS CDATA ""
        ENDDATE_MISMATCH_IDENTIFIER (Y|N) "N" 
        NEW_ENTITY_ID_MISMATCH (Y|N) "N" 
		BENCHMARK_RIC_MOVEMENT_MSG_TYPES CDATA ""
		BENCHMARK_RIC_ID_CTXT CDATA ""
		MSGTYPES_IDENTIFIER_MOVEMENT CDATA ""
		CREATE_MERGE_INSTRUCTION (Y|N|TRUE|FALSE) "N"
	  	ADDITIONAL_IDENTIFIERS_TO_BE_MOVED CDATA ""
		PREF_ENTITY_NME CDATA ""
		PREF_ENTITY_CTXT_TYP CDATA ""
		PREF_ENTITY_ID CDATA ""
		NO_SAME_SOURCE_MERGE_INSTRUCTION (Y|N) "N"
	  	LOG_MERGE_INSTRUCTION_BASED_ON_VSH (Y|N) "N"
		ENTITY_TYP_COLNME CDATA ""
		META_DATA_TABLE (Y|N) "N">
<!ELEMENT IDENTIFIER (MATCHKEYSET)*>
<!ATTLIST IDENTIFIER
	SEGMENT_TYPE (IssueIdentifier | IssuerIdentifier | FinsRoleIdentifier | FinancialMarketIdentifier | FinancialInstitutionIdentifier | CustomerIdentifier | EmployeeIdentifier | MarketIndexAlternateIdentifier | EmployeeRoleIdentifier
	             |DealerAlternateIdentifier | DealerBranchAlternateIdentifier | DealerRepresentativeAlternateIdentifier | FinsServicesProAltIdentifier | BNCHIdentifier | PRODProductAlternateIdentifier | PARTPartyIdentifier | PPRYPropertyIdentifier | GeographicUnitIdentifier | WCRDGSWClassificationReportDetails ) #REQUIRED
	FLD_CTXT CDATA #REQUIRED
	FLD_ID CDATA #REQUIRED>
<!ELEMENT MATCHKEYSET EMPTY>
<!ATTLIST MATCHKEYSET
	ID_CONTEXT CDATA #REQUIRED
	MATCH CDATA #REQUIRED
 	ERRLVL_LKUP_NOTFND ( ERROR | FATAL)  #IMPLIED
 	UNIQUE_ACROSS_MARKET ( TRUE | FALSE)  #IMPLIED>

=== kmishra-cell/gs_custom_build/configuration/Reference/streetreffiles/IDUniquenessCheckMatchKeySet.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE IDUniquenessCheckMatchKeySet SYSTEM "IDUniquenessCheckMatchKeySet.dtd">
<IDUniquenessCheckMatchKeySet>
	<ENTITY NAME="Issue" TYPE="ISSU" MATCH_FIELD=".INSTR_ID" NEED_PREVALIDATION="Y" LOOKUPID_REQUIRED="N" PRIMARY_IDENTIFIER="ISO CURR" SECONDARY_IDENTIFIER="" DUMMY_ACTIVITY_STATUS="PENDING" ENDDATE_MISMATCH_IDENTIFIER="N" NEW_ENTITY_ID_MISMATCH="N" BENCHMARK_RIC_MOVEMENT_MSG_TYPES="ReutersBondIssuanceSummary,ReutersCrossReferenceDataIdentifiers" BENCHMARK_RIC_ID_CTXT="RIC" MSGTYPES_IDENTIFIER_MOVEMENT="" PREF_ENTITY_NME="PREF_ISS_NME" PREF_ENTITY_CTXT_TYP="PREF_ID_CTXT_TYP" PREF_ENTITY_ID="PREF_ISS_ID" ENTITY_TYP_COLNME="ISS_TYP">
		<IDENTIFIER SEGMENT_TYPE="IssueIdentifier" FLD_CTXT=".ID_CTXT_TYP" FLD_ID=".ISS_ID">
			<MATCHKEYSET ID_CONTEXT="PAIRRED" MATCH="ISID_INSTR_CTXT_ID_USG"/>
			<MATCHKEYSET ID_CONTEXT="CPBBUNIQ" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="CPSEDOL" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="CUSIP" MATCH="ISID_CTXT_ID_USG"/>
			<MATCHKEYSET ID_CONTEXT="BBCUSIP" MATCH="ISID3_ID_CTXT_ISS_ID"/>
			<MATCHKEYSET ID_CONTEXT="BBUNIQUE" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="CPTICKER" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="SEDOL" MATCH="ISID_CTXT_ID_USG" UNIQUE_ACROSS_MARKET="TRUE"/>
			<MATCHKEYSET ID_CONTEXT="AUSTRIA" MATCH="ISID5_CTXT_ISSID_MKT"/>
			<MATCHKEYSET ID_CONTEXT="BELGIUM" MATCH="ISID5_CTXT_ISSID_MKT"/>
			<MATCHKEYSET ID_CONTEXT="CEDEL" MATCH="ISID5_CTXT_ISSID_MKT"/>
			<MATCHKEYSET ID_CONTEXT="DANISH" MATCH="ISID5_CTXT_ISSID_MKT"/>
			<MATCHKEYSET ID_CONTEXT="EUROCLR" MATCH="ISID5_CTXT_ISSID_MKT"/>
			<MATCHKEYSET ID_CONTEXT="XTRAKTER" MATCH="ISID5_CTXT_ISSID_MKT"/>
			<MATCHKEYSET ID_CONTEXT="ITALY" MATCH="ISID5_CTXT_ISSID_MKT"/>
			<MATCHKEYSET ID_CONTEXT="JAPAN" MATCH="ISID5_CTXT_ISSID_MKT"/>
			<MATCHKEYSET ID_CONTEXT="CBOSN" MATCH="ISID5_CTXT_ISSID_MKT"/>
			<MATCHKEYSET ID_CONTEXT="SEDOL2" MATCH="ISID5_CTXT_ISSID_MKT"/>
			<MATCHKEYSET ID_CONTEXT="SEDOL3" MATCH="ISID5_CTXT_ISSID_MKT"/>
			<MATCHKEYSET ID_CONTEXT="SEDOL4" MATCH="ISID5_CTXT_ISSID_MKT"/>
			<MATCHKEYSET ID_CONTEXT="SEDOL5" MATCH="ISID5_CTXT_ISSID_MKT"/>
			<MATCHKEYSET ID_CONTEXT="SPAIN" MATCH="ISID5_CTXT_ISSID_MKT"/>
			<MATCHKEYSET ID_CONTEXT="SWEDISH" MATCH="ISID5_CTXT_ISSID_MKT"/>
			<MATCHKEYSET ID_CONTEXT="VALOREN" MATCH="ISID5_CTXT_ISSID_MKT"/>
			<MATCHKEYSET ID_CONTEXT="WPK" MATCH="ISID5_CTXT_ISSID_MKT"/>
			<MATCHKEYSET ID_CONTEXT="ISIN" MATCH="ISID_CTXT_ID_USG"/>
			<MATCHKEYSET ID_CONTEXT="TICKER" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="DUNS" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="DUTCH" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="COMMON" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="SICOVAM" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="INTRNLID" MATCH="ISID3_ID_CTXT_ISS_ID" ERRLVL_LKUP_NOTFND="FATAL"/>
			<MATCHKEYSET ID_CONTEXT="LISTSYMB" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="TELEKURS" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="OTHERS" MATCH="ISID3_ID_CTXT_ISS_ID"/>
			<MATCHKEYSET ID_CONTEXT="RIC" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="BBCMPSEC" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="BBCPTICK" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="BBERG" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="CINS" MATCH="ISID_CTXT_ID_USG"/>
			<MATCHKEYSET ID_CONTEXT="PREFSYMB" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="ROOTSYMB" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="OTHSYMB" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="AII" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="TRDGSYMB" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="SECREF" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="WI-TICKER" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="RTTRCHID" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="BB8CHR" MATCH="ISID3_ID_CTXT_ISS_ID"/>
			<MATCHKEYSET ID_CONTEXT="TRANCHE_DEAL" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="SETTLECODE" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="BBYKEY" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="BNGLDESH" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="BOLIVIA" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="BRAZIL" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="BULGARIA" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="CROATIA" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="ESTONIA" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="GHANA" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="GREECE" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="INDIA" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="ISRAEL" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="IVCOAST" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="JAPAN" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="KOREA" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="LATVIA" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="LITHUANA" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="MALAYSIA" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="NAMIBIA" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="PAKISTAN" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="PALESTIN" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="POLAND" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="SIIB" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="ROMANIA" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="SLOVENIA" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="SAFRICA" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="SRILANKA" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="SWISS" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="TRINIDAD" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="TURKEY" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="CVM" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="QUICK" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="LUX" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="EXTICKER" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="OCCCODE" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="CPTICKER" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="RTTICKER" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="EQFUNDTK" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="BBUNQTCK" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="BRIDGE" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="MDYDBTNO" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="SNPINSTR" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="OCC" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="OPRA" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="BBIDSEC" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="EURONEXT" MATCH="ISID5_CTXT_ISSID_MKT"/>
			<MATCHKEYSET ID_CONTEXT="LEGID" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="TRADEID" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="BBGLOBAL" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="EMBSECID" MATCH="ISID3_ID_CTXT_ISS_ID"/>
			<MATCHKEYSET ID_CONTEXT="EMBSISSID" MATCH="ISID3_ID_CTXT_ISS_ID"/>
			<MATCHKEYSET ID_CONTEXT="EMBSPREF" MATCH="ISID3_ID_CTXT_ISS_ID"/>
			<MATCHKEYSET ID_CONTEXT="CSTICKER" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="GSFNOID" MATCH="ISID5_CTXT_ISSID_MKT"/>
			<MATCHKEYSET ID_CONTEXT="FULLSYMB" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="BBTRDGSYMB" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="SNPTRDGSYMB" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="TKTRDGSYMB" MATCH="ISID15_CTX_ID_MKT_USG_TNGCUR"/>
			<MATCHKEYSET ID_CONTEXT="WI-BBCMPSEC" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="WI-BBCPTICK" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="WI-BBTICKEXH" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="WI-SEDOL" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="WI-WPK" MATCH="ISID5_CTXT_ISSID_MKT"/>
			<MATCHKEYSET ID_CONTEXT="WI-DUTCH" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="WI-VALOREN" MATCH="ISID5_CTXT_ISSID_MKT"/>
			<MATCHKEYSET ID_CONTEXT="WI-SICOVAM" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="WI-BELGIUM" MATCH="ISID5_CTXT_ISSID_MKT"/>
			<MATCHKEYSET ID_CONTEXT="WI-COMMON" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="WI-CUSIP" MATCH="ISID_CTXT_ID_USG"/>
			<MATCHKEYSET ID_CONTEXT="WI-ISIN" MATCH="ISID_CTXT_ID_USG"/>
			<MATCHKEYSET ID_CONTEXT="WI-TRDGSYMB" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="ALTINSTID" MATCH="ISID3_ID_CTXT_ISS_ID"/>
			<MATCHKEYSET ID_CONTEXT="CPGLOBAL" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="RTTRCHID" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="ILX" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="FEEDINSID" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="QUOTEID" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="TRDSYMIL" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="WI-TRDSYMIL" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="WI-QUOTEID" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="WI-ILX" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="WI-RTTICKER" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="WI-RIC" MATCH="ISID6_CTX_ID_MKT_USG"/>
			<MATCHKEYSET ID_CONTEXT="WI-TICKER" MATCH="ISID6_CTX_ID_MKT_USG"/>
