=== kmishra-cell/gs_custom_build/configuration/Reference/streetreffiles/ScheduleMaintenance.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT EffEndDteColumnName (#PCDATA)>
<!ELEMENT EffStartDteColumnName (#PCDATA)>
<!ELEMENT ScheduleMaintenanceConfiguration (occurrence+)>
<!ELEMENT attribute (#PCDATA)>
<!ELEMENT occurrence (option)>
<!ATTLIST occurrence
	table (ft_t_firt | ft_t_irrt | ft_t_isrt | ft_t_rtop) #REQUIRED
>
<!ELEMENT option (attribute, EffStartDteColumnName, EffEndDteColumnName)>
<!ATTLIST option
	id (FIRT_1 | IRRT_1 | ISRT_1 | RTOP_1) #REQUIRED
	MatchingTolerance CDATA #IMPLIED
	messageTypes CDATA #IMPLIED
>

=== kmishra-cell/gs_custom_build/configuration/Reference/streetreffiles/ScheduleMaintenance.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ScheduleMaintenanceConfiguration SYSTEM "ScheduleMaintenance.dtd">
<ScheduleMaintenanceConfiguration>
	<occurrence table="ft_t_isrt">
		<option id="ISRT_1">
			<attribute>RTNG_CDE</attribute>
			<EffStartDteColumnName>RTNG_EFF_TMS</EffStartDteColumnName>
			<EffEndDteColumnName>SYS_EFF_END_TMS</EffEndDteColumnName>
		</option>
	</occurrence>
	<occurrence table="ft_t_firt">
		<option id="FIRT_1">
			<attribute>RTNG_CDE</attribute>
			<EffStartDteColumnName>RTNG_EFF_TMS</EffStartDteColumnName>
			<EffEndDteColumnName>SYS_EFF_END_TMS</EffEndDteColumnName>
		</option>
	</occurrence>
	<occurrence table="ft_t_irrt">
		<option id="IRRT_1">
			<attribute>RTNG_CDE</attribute>
			<EffStartDteColumnName>RTNG_EFF_TMS</EffStartDteColumnName>
			<EffEndDteColumnName>SYS_EFF_END_TMS</EffEndDteColumnName>
		</option>
	</occurrence>
	<occurrence table="ft_t_rtop">
		<option id="RTOP_1">
			<attribute>RTNG_OPINION_STAT_TYP</attribute>
			<EffStartDteColumnName>RTNG_OPINION_EFF_TMS</EffStartDteColumnName>
			<EffEndDteColumnName>SYS_EFF_END_TMS</EffEndDteColumnName>
		</option>
	</occurrence>
</ScheduleMaintenanceConfiguration>
